### ISSUE TITLE
New resource: Tracking fields

### ISSUE THREAD

**Issue by Jericho** [Jericho/ZoomNet#16]
Add the tracking fields resource

- [x] Create a tracking field
- [x] Delete a tracking field
- [x] Get a tracking field
- [x] List tracking fields
- [ ] Update a tracking field

https://developers.zoom.us/docs/api/rest/reference/zoom-api/methods/#tag/Tracking-Field

**Comment by Jericho** [comment]
My account does not have access to this functionality. I get `Access restricted, you do not have the privilege to perform this action` when I attempt to retrieve the list of existing tracking fields
